export type DropDef={itemId:string;rate:number}
export type MapDef={id:string;name:string;minLevel:number;monsterId:number;monster:string;monsterLevel:number;monsterHp:number;monsterAtk:number;monsterDef:number;race:string;element:string;exp:number;jobExp:number;zeny:number;bg:string;drops:DropDef[]}
export type ItemDef={id:string;aegisId?:number;aegisName?:string;name:string;type:'material'|'consumable'|'card'|'equipment';icon:string;rarity:'common'|'uncommon'|'rare'|'epic';buy?:number;sell?:number;weight?:number;attack?:number;defense?:number;hp?:number;sp?:number;slot?:'weapon'|'armor'|'shield';equipLevel?:number;cardBonus?:{attack?:number;defense?:number;hp?:number;sp?:number;drop?:number};source?:'rAthena'|'game'}
export type StatKey='str'|'agi'|'vit'|'int'|'dex'|'luk'
export type ClassDef={id:string;name:string;icon:string;description:string;minBase:number;minJob:number;bonuses:Partial<Record<StatKey,number>>}
export type SkillDef={id:string;aegisId?:number;aegisName?:string;name:string;icon:string;description:string;maxLevel:number;spCost:number;cooldown:number;jobPointCost:number;classId:string;kind:'damage'|'heal'|'buff'|'passive';power:number;requires?:{skillId:string;level:number};element?:string;source?:'rAthena'|'game'}
export type QuestDef={id:string;name:string;description:string;type:'kill'|'item';target:string;amount:number;reward:{exp?:number;job?:number;zeny?:number;itemId?:string;itemQty?:number}}

const d=(itemId:string,rate:number):DropDef=>({itemId,rate})

// Progressão baseada no mob_db Renewal do rAthena. Rates seguem escala 0..10000.
export const maps:MapDef[]=[
  {id:'prontera-field',name:'Prontera Field',minLevel:1,monsterId:1002,monster:'Poring',monsterLevel:1,monsterHp:55,monsterAtk:1,monsterDef:2,race:'Plant',element:'Water 1',exp:150,jobExp:40,zeny:8,bg:'meadow',drops:[d('jellopy',7000),d('knife',100),d('stickyMucus',400),d('apple',1000),d('flyWing',500),d('unripeApple',20),d('poringCard',20)]},
  {id:'south-prontera',name:'South Prontera',minLevel:2,monsterId:1113,monster:'Drops',monsterLevel:2,monsterHp:46,monsterAtk:1,monsterDef:16,race:'Plant',element:'Fire 1',exp:150,jobExp:45,zeny:9,bg:'meadow',drops:[d('jellopy',7000),d('stickyMucus',600),d('apple',1400),d('flyWing',500),d('dropsCard',20)]},
  {id:'lunatic-meadow',name:'Lunatic Meadow',minLevel:3,monsterId:1063,monster:'Lunatic',monsterLevel:3,monsterHp:48,monsterAtk:1,monsterDef:18,race:'Brute',element:'Neutral 1',exp:150,jobExp:50,zeny:10,bg:'meadow',drops:[d('clover',7000),d('feather',3000),d('carrot',3000),d('flyWing',500),d('lunaticCard',20)]},
  {id:'pupa-grove',name:'Pupa Grove',minLevel:4,monsterId:1008,monster:'Pupa',monsterLevel:4,monsterHp:51,monsterAtk:1,monsterDef:24,race:'Insect',element:'Earth 1',exp:157,jobExp:55,zeny:11,bg:'forest',drops:[d('chrysalis',7000),d('stickyMucus',700),d('shell',1000),d('ironOre',500),d('pupaCard',1)]},
  {id:'chonchon-road',name:'Chonchon Road',minLevel:5,monsterId:1011,monster:'Chonchon',monsterLevel:5,monsterHp:48,monsterAtk:1,monsterDef:27,race:'Insect',element:'Wind 1',exp:150,jobExp:60,zeny:12,bg:'plains',drops:[d('shell',7000),d('jellopy',2000),d('ironOre',200),d('flyWing',500),d('chonchonCard',20)]},
  {id:'geffen-plains',name:'Geffen Plains',minLevel:6,monsterId:1007,monster:'Fabre',monsterLevel:6,monsterHp:59,monsterAtk:1,monsterDef:24,race:'Insect',element:'Earth 1',exp:158,jobExp:65,zeny:14,bg:'plains',drops:[d('fluff',7000),d('feather',1000),d('club',80),d('greenHerb',3000),d('clover',1000),d('fabreCard',20)]},
  {id:'payon-forest',name:'Payon Forest',minLevel:8,monsterId:1010,monster:'Willow',monsterLevel:8,monsterHp:78,monsterAtk:1,monsterDef:38,race:'Plant',element:'Earth 1',exp:160,jobExp:75,zeny:18,bg:'forest',drops:[d('treeRoot',9000),d('resin',2000),d('sweetPotato',1000),d('woodenBlock',100),d('willowCard',10)]},
  {id:'mandragora-field',name:'Mandragora Field',minLevel:13,monsterId:1020,monster:'Mandragora',monsterLevel:13,monsterHp:140,monsterAtk:4,monsterDef:13,race:'Plant',element:'Earth 1',exp:170,jobExp:100,zeny:24,bg:'forest',drops:[d('stem',8000),d('greenHerb',400),d('flyWing',500),d('mandragoraCard',1)]},
  {id:'rocker-hill',name:'Rocker Hill',minLevel:15,monsterId:1052,monster:'Rocker',monsterLevel:15,monsterHp:155,monsterAtk:6,monsterDef:16,race:'Insect',element:'Earth 1',exp:174,jobExp:110,zeny:27,bg:'plains',drops:[d('grasshopperLeg',8000),d('flyWing',500),d('javelin',80),d('rockerCard',1)]},
  {id:'spore-woods',name:'Spore Woods',minLevel:18,monsterId:1014,monster:'Spore',monsterLevel:18,monsterHp:223,monsterAtk:8,monsterDef:12,race:'Plant',element:'Water 1',exp:175,jobExp:125,zeny:32,bg:'forest',drops:[d('mushroomSpore',8000),d('redHerb',1000),d('strawberry',600),d('flyWing',500),d('sporeCard',10)]},
  {id:'creamy-garden',name:'Creamy Garden',minLevel:23,monsterId:1018,monster:'Creamy',monsterLevel:23,monsterHp:247,monsterAtk:16,monsterDef:28,race:'Insect',element:'Wind 1',exp:196,jobExp:148,zeny:38,bg:'meadow',drops:[d('butterflyPowder',8000),d('honey',200),d('flower',500),d('flyWing',500),d('creamyCard',1)]},
  {id:'muka-desert',name:'Muka Desert',minLevel:23,monsterId:1055,monster:'Muka',monsterLevel:23,monsterHp:337,monsterAtk:19,monsterDef:28,race:'Plant',element:'Earth 1',exp:205,jobExp:148,zeny:41,bg:'desert',drops:[d('cactusNeedle',4500),d('greenHerb',200),d('redHerb',500),d('ironOre',125),d('mukaCard',1)]},
  {id:'peco-savanna',name:'Peco Peco Savanna',minLevel:25,monsterId:1019,monster:'Peco Peco',monsterLevel:25,monsterHp:354,monsterAtk:23,monsterDef:48,race:'Brute',element:'Fire 1',exp:204,jobExp:156,zeny:44,bg:'desert',drops:[d('billOfBirds',4500),d('yellowHerb',100),d('orange',500),d('flyWing',500),d('pecoCard',1)]},
  {id:'smokie-woods',name:'Smokie Woods',minLevel:29,monsterId:1056,monster:'Smokie',monsterLevel:29,monsterHp:414,monsterAtk:29,monsterDef:26,race:'Brute',element:'Earth 1',exp:235,jobExp:176,zeny:52,bg:'forest',drops:[d('raccoonLeaf',2750),d('sweetPotato',400),d('flyWing',500),d('smokieCard',1)]},
  {id:'poporing-marsh',name:'Poporing Marsh',minLevel:30,monsterId:1031,monster:'Poporing',monsterLevel:30,monsterHp:489,monsterAtk:31,monsterDef:36,race:'Plant',element:'Poison 1',exp:229,jobExp:181,zeny:55,bg:'swamp',drops:[d('stickyMucus',6000),d('greenHerb',1000),d('grape',200),d('mainGauche',20),d('poporingCard',10)]},
  {id:'elder-grove',name:'Elder Willow Grove',minLevel:34,monsterId:1033,monster:'Elder Willow',monsterLevel:34,monsterHp:535,monsterAtk:43,monsterDef:45,race:'Plant',element:'Fire 2',exp:259,jobExp:210,zeny:64,bg:'forest',drops:[d('resin',4500),d('eluniumStone',20),d('deadBranch',50),d('elderWillowCard',1)]},
  {id:'yoyo-jungle',name:'Yoyo Jungle',minLevel:38,monsterId:1057,monster:'Yoyo',monsterLevel:38,monsterHp:694,monsterAtk:55,monsterDef:40,race:'Brute',element:'Earth 1',exp:300,jobExp:237,zeny:75,bg:'forest',drops:[d('yoyoTail',4500),d('banana',750),d('cacao',450),d('strawberry',500),d('yoyoCard',1)]},
  {id:'wolf-den',name:'Wolf Den',minLevel:45,monsterId:1013,monster:'Wolf',monsterLevel:45,monsterHp:1091,monsterAtk:89,monsterDef:55,race:'Brute',element:'Earth 1',exp:369,jobExp:301,zeny:92,bg:'forest',drops:[d('wolfClaw',4500),d('animalSkin',2750),d('strawberry',300),d('wolfCard',1)]},
  {id:'steel-canyon',name:'Steel Chonchon Canyon',minLevel:48,monsterId:1042,monster:'Steel Chonchon',monsterLevel:48,monsterHp:985,monsterAtk:84,monsterDef:57,race:'Insect',element:'Wind 1',exp:379,jobExp:328,zeny:98,bg:'plains',drops:[d('steel',15),d('shell',4500),d('iron',100),d('steelChonchonCard',1)]},
  {id:'golem-quarry',name:'Golem Quarry',minLevel:61,monsterId:1040,monster:'Golem',monsterLevel:61,monsterHp:2324,monsterAtk:172,monsterDef:190,race:'Formless',element:'Neutral 3',exp:564,jobExp:508,zeny:145,bg:'desert',drops:[d('stoneHeart',4500),d('steel',75),d('eluniumStone',35),d('iron',175),d('golemCard',1)]},
  {id:'sandman-dunes',name:'Sandman Dunes',minLevel:61,monsterId:1165,monster:'Sandman',monsterLevel:61,monsterHp:2324,monsterAtk:188,monsterDef:126,race:'Formless',element:'Earth 3',exp:592,jobExp:508,zeny:152,bg:'desert',drops:[d('grit',2668),d('fineSand',175),d('eluniumStone',59),d('sandmanCard',1)]},
  {id:'hode-cavern',name:'Hode Cavern',minLevel:63,monsterId:1127,monster:'Hode',monsterLevel:63,monsterHp:2347,monsterAtk:194,monsterDef:91,race:'Brute',element:'Earth 2',exp:617,jobExp:532,zeny:160,bg:'desert',drops:[d('earthwormPeeling',4500),d('stickyMucus',1500),d('eluniumStone',40),d('hodeCard',1)]},
  {id:'argiope-nest',name:'Argiope Nest',minLevel:75,monsterId:1099,monster:'Argiope',monsterLevel:75,monsterHp:3570,monsterAtk:270,monsterDef:88,race:'Insect',element:'Poison 1',exp:794,jobExp:734,zeny:220,bg:'swamp',drops:[d('shortLeg',2668),d('greenHerb',750),d('eluniumStone',88),d('argiopeCard',1)]},
]

const material=(id:string,name:string,icon='◆',buy=20,rarity:ItemDef['rarity']='common'):ItemDef=>({id,name,type:'material',icon,rarity,buy,sell:Math.max(1,Math.floor(buy*.45)),source:'rAthena'})
const card=(id:string,name:string,bonus:ItemDef['cardBonus']):ItemDef=>({id,name,type:'card',icon:'▣',rarity:'rare',buy:20,sell:250,cardBonus:bonus,source:'rAthena'})
export const items:Record<string,ItemDef>={
  jellopy:material('jellopy','Jellopy','◆',6),stickyMucus:material('stickyMucus','Sticky Mucus','◉',70),clover:material('clover','Clover','♣',10),feather:material('feather','Feather','⌁',20),chrysalis:material('chrysalis','Chrysalis','⬡',30),shell:material('shell','Shell','◌',25),ironOre:material('ironOre','Iron Ore','⬢',50),fluff:material('fluff','Fluff','✦',8),treeRoot:material('treeRoot','Tree Root','⌁',12),resin:material('resin','Resin','⬢',120),woodenBlock:material('woodenBlock','Wooden Block','▰',90,'uncommon'),stem:material('stem','Stem','╱',30),grasshopperLeg:material('grasshopperLeg',"Grasshopper's Leg",'⌁',45),mushroomSpore:material('mushroomSpore','Mushroom Spore','●',55),butterflyPowder:material('butterflyPowder','Powder of Butterfly','✧',70),cactusNeedle:material('cactusNeedle','Cactus Needle','╱',65),billOfBirds:material('billOfBirds','Bill of Birds','⌁',55),raccoonLeaf:material('raccoonLeaf','Raccoon Leaf','♣',80),eluniumStone:material('eluniumStone','Rough Elunium','⬟',400,'uncommon'),deadBranch:material('deadBranch','Dead Branch','⌁',800,'rare'),yoyoTail:material('yoyoTail','Yoyo Tail','⌁',90),wolfClaw:material('wolfClaw','Claw of Wolves','⌁',110),animalSkin:material('animalSkin','Animal Skin','▰',60),steel:material('steel','Steel','⬢',1000,'uncommon'),iron:material('iron','Iron','⬢',100),stoneHeart:material('stoneHeart','Stone Heart','◆',140),grit:material('grit','Grit','◆',90),fineSand:material('fineSand','Fine Sand','◆',75),earthwormPeeling:material('earthwormPeeling','Earthworm Peeling','⌁',95),shortLeg:material('shortLeg','Short Leg','⌁',120),
  apple:{id:'apple',name:'Apple',type:'consumable',icon:'●',rarity:'common',buy:15,sell:7,hp:50,source:'rAthena'},flyWing:{id:'flyWing',name:'Fly Wing',type:'consumable',icon:'➤',rarity:'uncommon',buy:250,sell:50,source:'rAthena'},carrot:{id:'carrot',name:'Carrot',type:'consumable',icon:'●',rarity:'common',buy:15,sell:7,hp:60,source:'rAthena'},greenHerb:{id:'greenHerb',name:'Green Herb',type:'consumable',icon:'♣',rarity:'common',buy:18,sell:8,hp:70,source:'rAthena'},redHerb:{id:'redHerb',name:'Red Herb',type:'consumable',icon:'♣',rarity:'common',buy:18,sell:8,hp:90,source:'rAthena'},sweetPotato:{id:'sweetPotato',name:'Sweet Potato',type:'consumable',icon:'●',rarity:'common',buy:15,sell:7,hp:80,source:'rAthena'},strawberry:{id:'strawberry',name:'Strawberry',type:'consumable',icon:'●',rarity:'uncommon',buy:120,sell:30,sp:35,source:'rAthena'},honey:{id:'honey',name:'Honey',type:'consumable',icon:'●',rarity:'uncommon',buy:500,sell:100,hp:180,sp:60,source:'rAthena'},flower:material('flower','Flower','✿',20),yellowHerb:{id:'yellowHerb',name:'Yellow Herb',type:'consumable',icon:'♣',rarity:'common',buy:40,sell:15,hp:120,source:'rAthena'},orange:{id:'orange',name:'Orange',type:'consumable',icon:'●',rarity:'common',buy:30,sell:12,hp:100,source:'rAthena'},grape:{id:'grape',name:'Grape',type:'consumable',icon:'●',rarity:'uncommon',buy:200,sell:50,sp:45,source:'rAthena'},banana:{id:'banana',name:'Banana',type:'consumable',icon:'●',rarity:'common',buy:20,sell:8,hp:90,source:'rAthena'},cacao:material('cacao','Cacao','●',70),unripeApple:material('unripeApple','Unripe Apple','●',500,'rare'),
  noviceSword:{id:'noviceSword',name:'Novice Sword',type:'equipment',icon:'⚔',rarity:'common',attack:18,slot:'weapon',equipLevel:1,buy:250,sell:100,source:'game'},knife:{id:'knife',name:'Knife [4]',type:'equipment',icon:'🗡',rarity:'uncommon',attack:17,slot:'weapon',equipLevel:1,buy:50,sell:25,source:'rAthena'},club:{id:'club',name:'Club [4]',type:'equipment',icon:'⚒',rarity:'uncommon',attack:23,slot:'weapon',equipLevel:2,buy:120,sell:55,source:'rAthena'},javelin:{id:'javelin',name:'Javelin',type:'equipment',icon:'➶',rarity:'uncommon',attack:28,slot:'weapon',equipLevel:8,buy:400,sell:160,source:'rAthena'},mainGauche:{id:'mainGauche',name:'Main Gauche',type:'equipment',icon:'🗡',rarity:'rare',attack:43,slot:'weapon',equipLevel:20,buy:2400,sell:900,source:'rAthena'},adventurerArmor:{id:'adventurerArmor',name:"Adventurer's Suit",type:'equipment',icon:'◈',rarity:'uncommon',defense:20,slot:'armor',equipLevel:1,buy:1000,sell:400,source:'rAthena'},ironShield:{id:'ironShield',name:'Iron Shield',type:'equipment',icon:'⬟',rarity:'uncommon',defense:9,slot:'shield',equipLevel:1,buy:900,sell:350,source:'game'},guard:{id:'guard',name:'Guard [1]',type:'equipment',icon:'⬟',rarity:'uncommon',defense:20,slot:'shield',equipLevel:5,buy:1800,sell:700,source:'rAthena'},
  poringCard:card('poringCard','Poring Card',{hp:100}),dropsCard:card('dropsCard','Drops Card',{attack:3}),lunaticCard:card('lunaticCard','Lunatic Card',{attack:2,hp:40}),pupaCard:card('pupaCard','Pupa Card',{hp:700}),chonchonCard:card('chonchonCard','Chonchon Card',{defense:3}),fabreCard:card('fabreCard','Fabre Card',{hp:100,attack:2}),willowCard:card('willowCard','Willow Card',{sp:80}),mandragoraCard:card('mandragoraCard','Mandragora Card',{attack:4}),rockerCard:card('rockerCard','Rocker Card',{attack:5,hp:50}),sporeCard:card('sporeCard','Spore Card',{defense:4}),creamyCard:card('creamyCard','Creamy Card',{drop:5}),mukaCard:card('mukaCard','Muka Card',{hp:120}),pecoCard:card('pecoCard','Peco Peco Card',{hp:300}),smokieCard:card('smokieCard','Smokie Card',{defense:6}),poporingCard:card('poporingCard','Poporing Card',{attack:8}),elderWillowCard:card('elderWillowCard','Elder Willow Card',{sp:120}),yoyoCard:card('yoyoCard','Yoyo Card',{attack:7,defense:4}),wolfCard:card('wolfCard','Wolf Card',{attack:12}),steelChonchonCard:card('steelChonchonCard','Steel Chonchon Card',{defense:10}),golemCard:card('golemCard','Golem Card',{defense:18}),sandmanCard:card('sandmanCard','Sandman Card',{hp:250}),hodeCard:card('hodeCard','Hode Card',{defense:12}),argiopeCard:card('argiopeCard','Argiope Card',{hp:400,defense:15}),
}

export const shopItems=['apple','redHerb','greenHerb','strawberry','flyWing','noviceSword','adventurerArmor','ironShield','guard']

export const classes:ClassDef[]=[
  {id:'novice',name:'Novice',icon:'✦',description:'Classe inicial. Alcance Base Lv. 10 e Job Lv. 10 para escolher sua primeira vocação.',minBase:1,minJob:1,bonuses:{}},
  {id:'swordsman',name:'Swordsman',icon:'⚔',description:'Especialista em combate corpo a corpo, força e resistência.',minBase:10,minJob:10,bonuses:{str:3,vit:3}},
  {id:'mage',name:'Mage',icon:'✹',description:'Especialista em magia ofensiva, INT e DEX.',minBase:10,minJob:10,bonuses:{int:4,dex:2}},
  {id:'archer',name:'Archer',icon:'➹',description:'Ataques à distância com alta precisão e velocidade.',minBase:10,minJob:10,bonuses:{dex:4,agi:2}},
  {id:'acolyte',name:'Acolyte',icon:'✚',description:'Cura, suporte e grande resistência espiritual.',minBase:10,minJob:10,bonuses:{int:2,vit:2,luk:2}},
  {id:'thief',name:'Thief',icon:'☽',description:'Velocidade, esquiva e golpes críticos.',minBase:10,minJob:10,bonuses:{agi:4,luk:2}},
]

export const skills:SkillDef[]=[
  {id:'basicSkill',name:'Basic Skill',icon:'✦',description:'Fundamentos básicos do Novice.',maxLevel:9,spCost:0,cooldown:0,jobPointCost:1,classId:'novice',kind:'passive',power:1.02,source:'rAthena'},
  {id:'firstAid',name:'First Aid',icon:'✚',description:'Primeiros socorros.',maxLevel:1,spCost:3,cooldown:5,jobPointCost:1,classId:'novice',kind:'heal',power:.12,source:'rAthena'},
  {id:'bash',name:'Bash',icon:'💥',description:'Golpe físico poderoso.',maxLevel:10,spCost:8,cooldown:2,jobPointCost:1,classId:'swordsman',kind:'damage',power:1.65,source:'rAthena'},
  {id:'provoke',name:'Provoke',icon:'❗',description:'Adaptado como buff ofensivo no modo idle.',maxLevel:10,spCost:4,cooldown:8,jobPointCost:1,classId:'swordsman',kind:'buff',power:1.15,requires:{skillId:'bash',level:3},source:'rAthena'},
  {id:'magnumBreak',name:'Magnum Break',icon:'🔥',description:'Ataque em área de fogo.',maxLevel:10,spCost:30,cooldown:3,jobPointCost:1,classId:'swordsman',kind:'damage',power:2.05,element:'Fire',requires:{skillId:'bash',level:5},source:'rAthena'},
  {id:'fireBolt',name:'Fire Bolt',icon:'🔥',description:'Bolt mágico de fogo.',maxLevel:10,spCost:12,cooldown:3,jobPointCost:1,classId:'mage',kind:'damage',power:1.75,element:'Fire',source:'rAthena'},
  {id:'coldBolt',name:'Cold Bolt',icon:'❄',description:'Bolt mágico de água.',maxLevel:10,spCost:12,cooldown:3,jobPointCost:1,classId:'mage',kind:'damage',power:1.72,element:'Water',source:'rAthena'},
  {id:'soulStrike',name:'Soul Strike',icon:'✹',description:'Ataque mágico Ghost.',maxLevel:10,spCost:18,cooldown:2,jobPointCost:1,classId:'mage',kind:'damage',power:2.1,element:'Ghost',requires:{skillId:'fireBolt',level:3},source:'rAthena'},
  {id:'owlEye',name:"Owl's Eye",icon:'◉',description:'Passiva de precisão.',maxLevel:10,spCost:0,cooldown:0,jobPointCost:1,classId:'archer',kind:'passive',power:1.02,source:'rAthena'},
  {id:'doubleStrafe',name:'Double Strafe',icon:'➹',description:'Dois disparos rápidos.',maxLevel:10,spCost:12,cooldown:2,jobPointCost:1,classId:'archer',kind:'damage',power:1.8,requires:{skillId:'owlEye',level:3},source:'rAthena'},
  {id:'arrowShower',name:'Arrow Shower',icon:'☄',description:'Chuva de flechas.',maxLevel:10,spCost:15,cooldown:3,jobPointCost:1,classId:'archer',kind:'damage',power:2,requires:{skillId:'doubleStrafe',level:5},source:'rAthena'},
  {id:'heal',name:'Heal',icon:'✚',description:'Cura sagrada.',maxLevel:10,spCost:13,cooldown:2,jobPointCost:1,classId:'acolyte',kind:'heal',power:.25,source:'rAthena'},
  {id:'blessing',name:'Blessing',icon:'✧',description:'Bênção de suporte.',maxLevel:10,spCost:28,cooldown:8,jobPointCost:1,classId:'acolyte',kind:'buff',power:1.18,requires:{skillId:'heal',level:3},source:'rAthena'},
  {id:'holyLight',name:'Holy Light',icon:'☀',description:'Ataque sagrado.',maxLevel:1,spCost:15,cooldown:2,jobPointCost:1,classId:'acolyte',kind:'damage',power:1.95,element:'Holy',requires:{skillId:'heal',level:5},source:'rAthena'},
  {id:'doubleAttack',name:'Double Attack',icon:'☽',description:'Passiva de golpes duplos.',maxLevel:10,spCost:0,cooldown:0,jobPointCost:1,classId:'thief',kind:'passive',power:1.025,source:'rAthena'},
  {id:'improveDodge',name:'Improve Dodge',icon:'➤',description:'Passiva de agilidade.',maxLevel:10,spCost:0,cooldown:0,jobPointCost:1,classId:'thief',kind:'passive',power:1.012,source:'rAthena'},
  {id:'envenom',name:'Envenom',icon:'☠',description:'Ataque venenoso.',maxLevel:10,spCost:12,cooldown:3,jobPointCost:1,classId:'thief',kind:'damage',power:2,element:'Poison',requires:{skillId:'doubleAttack',level:5},source:'rAthena'},
]

export const quests:QuestDef[]=[
  {id:'q-poring-50',name:'Limpeza de Porings',description:'Derrote 50 Porings em Prontera Field.',type:'kill',target:'Poring',amount:50,reward:{exp:2500,job:800,zeny:1200}},
  {id:'q-jellopy-30',name:'Coleta de Jellopy',description:'Tenha 30 Jellopys no inventário.',type:'item',target:'jellopy',amount:30,reward:{zeny:1800,itemId:'redHerb',itemQty:5}},
  {id:'q-willow-40',name:'Madeira de Payon',description:'Derrote 40 Willows.',type:'kill',target:'Willow',amount:40,reward:{exp:5000,job:2000,zeny:3000}},
  {id:'q-spore-60',name:'Esporos na floresta',description:'Derrote 60 Spores.',type:'kill',target:'Spore',amount:60,reward:{exp:8500,job:4000,zeny:5500,itemId:'strawberry',itemQty:10}},
  {id:'q-poporing-100',name:'Ameaça Venenosa',description:'Derrote 100 Poporings.',type:'kill',target:'Poporing',amount:100,reward:{exp:18000,job:9000,zeny:12000}},
  {id:'q-wolf-120',name:'Caçador de Lobos',description:'Derrote 120 Wolves.',type:'kill',target:'Wolf',amount:120,reward:{exp:30000,job:18000,zeny:22000,itemId:'honey',itemQty:5}},
]

export const startingInventory:Record<string,number>={apple:5,noviceSword:1,adventurerArmor:1}
