import { useState } from 'react'
import { Backpack, BookOpen, CircleUserRound, Crown, Gem, Map, RefreshCcw, Settings, Shield, ShoppingBag, Sparkles, Swords, Trophy, X } from 'lucide-react'
import { classes, items, maps, quests, shopItems, type StatKey } from './game/data'
import { useGame } from './game/useGame'

type Panel='Personagem'|'Equipamentos'|'Inventário'|'Skills'|'Mapas'|'Quests'|'Loja'|'Bestiário'|'Auto Hunt'|'Rebirth'|null
const menu=[[CircleUserRound,'Personagem'],[Shield,'Equipamentos'],[Backpack,'Inventário'],[Sparkles,'Skills'],[Map,'Mapas'],[BookOpen,'Quests'],[ShoppingBag,'Loja'],[Trophy,'Bestiário'],[Swords,'Auto Hunt'],[RefreshCcw,'Rebirth']] as const
const statLabels:Record<StatKey,string>={str:'STR',agi:'AGI',vit:'VIT',int:'INT',dex:'DEX',luk:'LUK'}
const rateLabel=(rate:number)=>`${(rate/100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`
const slots=[['weapon','Arma'],['armor','Armadura'],['shield','Escudo']] as const

export function App(){
  const g=useGame();const [panel,setPanel]=useState<Panel>(null)
  const hpPct=g.save.hp/g.save.maxHp*100,spPct=g.save.sp/g.save.maxSp*100,expPct=g.save.baseExp/g.baseNeed*100,jobPct=g.save.jobExp/g.jobNeed*100
  return <main className={`game-shell biome-${g.map.bg}`}>
    <section className="hud card"><img className={`portrait-img ${g.playerDead?'dead':''}`} src="/sprites/swordsman.svg"/><div className="hud-copy"><strong>Knock</strong><span>{g.classDef.name} · Rebirth {g.save.rebirths}</span><div className="levels"><span>Base Lv. {g.save.baseLevel}</span><span>Job Lv. {g.save.jobLevel}</span></div><div className="bar-row"><small>HP {Math.round(g.save.hp)}/{g.save.maxHp}</small><div className="meter hp"><i style={{width:`${hpPct}%`}}/></div></div><div className="bar-row"><small>SP {g.save.sp}/{g.save.maxSp}</small><div className="meter sp"><i style={{width:`${spPct}%`}}/></div></div></div></section>
    <section className="topbar"><div className="currency">🪙 <b>{g.save.zeny.toLocaleString('pt-BR')}</b> Zeny</div>{g.activeBuff&&<div className="currency buff-chip">✦ {g.activeBuff.name}</div>}<div className="currency"><Gem size={18}/> RP {g.save.rebirthPoints}</div><button className="icon-btn" onClick={()=>setPanel('Auto Hunt')}><Settings size={20}/></button></section>
    <aside className="side-menu card">{menu.map(([Icon,label])=><button key={label} onClick={()=>setPanel(label)}><Icon size={20}/><span>{label}</span></button>)}</aside>

    <section className="hunt-zone"><div className="sky"/><div className="cloud c1"/><div className="cloud c2"/><div className="mountains"/><div className="castle"><i/><i/><i/><span/></div><div className="far-trees"/><div className="field"/><div className="path"/><div className="pond"/><div className="tree tree-a"><i/><b/></div><div className="tree tree-b"><i/><b/></div><div className="tree tree-c"><i/><b/></div><div className="fence fence-a"/><div className="fence fence-b"/><div className="signpost"><b>{g.map.name.split(' ')[0]}</b></div>
      <div className={`sprite player-sprite ${g.save.running&&!g.playerDead?'attacking':''} ${g.playerDead?'dead':''}`} key={g.hit}><div className="sprite-shadow"/><img src="/sprites/swordsman.svg"/><div className="slash"/>{g.playerDead&&<span className="respawn-label">RESPAWN...</span>}</div>
      <div className={`sprite mob main-mob ${!g.monsterAlive?'dead':''}`}><div className="sprite-shadow"/><img src="/sprites/poring.svg"/><div className="mob-name">{g.map.monster} · Lv. {g.map.monsterLevel}</div><div className="mob-hp"><i style={{width:`${Math.max(0,g.monsterHp/g.map.monsterHp*100)}%`}}/></div>{g.damage>0&&g.monsterAlive&&<div className="damage-number" key={g.hit}>{g.damage}</div>}{!g.monsterAlive&&<span className="respawn-label mob-respawn">Respawn...</span>}</div>
      <div className="sprite mob mob-2 decorative"><img src="/sprites/poring.svg"/></div><div className="sprite mob mob-3 decorative"><img src="/sprites/poring.svg"/></div>
      <div className="battle-popups" key={g.save.kills}><strong>+{g.map.exp} EXP</strong><em>+{g.map.jobExp} Job EXP</em><span>+{g.map.zeny} Zeny</span></div><div className="world-label">{g.map.name}<small>Mob #{g.map.monsterId} · {g.map.element} · {g.map.race}</small></div>
    </section>

    <aside className="auto-hunt card"><div className="panel-title"><Swords size={20}/> AUTO HUNT</div><div className="stats"><p><span>Mapa:</span><b>{g.map.name}</b></p><p><span>Monstro:</span><b>{g.map.monster} Lv. {g.map.monsterLevel}</b></p><p><span>Elemento:</span><b>{g.map.element}</b></p><p><span>HP / DEF:</span><b>{g.map.monsterHp} / {g.map.monsterDef}</b></p><p><span>ATK efetivo:</span><b>{g.effectiveAttack}{g.activeBuff?' ↑':''}</b></p><p><span>EXP/Job:</span><b>{g.map.exp} / {g.map.jobExp}</b></p><p><span>Kills:</span><b>{g.save.kills.toLocaleString('pt-BR')}</b></p></div><div className="drops"><h3>Drop Table</h3>{g.map.drops.slice(0,6).map(dr=>{const it=items[dr.itemId];return it?<div key={dr.itemId} className={it.rarity==='rare'?'rare':''}><span>{it.icon} {it.name} <small>{rateLabel(dr.rate)}</small></span><b>x{g.save.inventory[dr.itemId]||0}</b></div>:null})}</div><button className={`stop-btn ${!g.save.running?'paused':''}`} onClick={g.toggle}>{g.save.running?'PARAR CAÇADA':'INICIAR CAÇADA'}</button></aside>

    <section className="skillbar card">{g.activeSkills.slice(0,8).map(sk=>{const lvl=g.save.skillLevels[sk.id]||0,cd=g.cooldowns[sk.id]||0;return <button key={sk.id} disabled={lvl<=0||cd>0||g.save.sp<sk.spCost} onClick={()=>g.useSkill(sk.id)} title={`${sk.name} Lv.${lvl}`}><span>{sk.icon}</span>{cd>0&&<small>{cd}s</small>}</button>})}{Array.from({length:Math.max(0,8-g.activeSkills.length)}).map((_,i)=><button key={i}>+</button>)}</section>
    <section className="expbar card"><div className="xp-line"><span>Base EXP</span><b>{expPct.toFixed(1)}%</b><div className="meter exp"><i style={{width:`${Math.min(100,expPct)}%`}}/></div></div><div className="xp-line job-line"><span>Job EXP</span><b>{jobPct.toFixed(1)}%</b><div className="meter job"><i style={{width:`${Math.min(100,jobPct)}%`}}/></div></div></section>
    <section className="chat card"><div className="chat-tabs"><b>Batalha</b><span>Sistema</span></div>{g.log.map((x,i)=><p key={i}>› {x}</p>)}</section><div className="brand"><Crown size={24}/> RAGNAROK <span>IDLE</span></div>

    {panel&&<div className="modal-backdrop" onMouseDown={()=>setPanel(null)}><section className="game-modal card mega-modal" onMouseDown={e=>e.stopPropagation()}><header><h2>{panel}</h2><button onClick={()=>setPanel(null)}><X/></button></header>{panel==='Personagem'&&<Character g={g}/>} {panel==='Inventário'&&<Inventory g={g}/>} {panel==='Equipamentos'&&<Equipment g={g}/>} {panel==='Mapas'&&<Maps g={g} close={()=>setPanel(null)}/>} {panel==='Skills'&&<Skills g={g}/>} {panel==='Loja'&&<Shop g={g}/>} {panel==='Bestiário'&&<Bestiary g={g}/>} {panel==='Quests'&&<Quests g={g}/>} {panel==='Auto Hunt'&&<AutoSettings g={g}/>} {panel==='Rebirth'&&<Rebirth g={g}/>}</section></div>}
    {g.offline&&<div className="modal-backdrop"><section className="offline-card card"><Crown/><h2>Bem-vindo de volta!</h2><p>Caçada offline por <b>{Math.floor(g.offline.seconds/60)} minutos</b>.</p><div className="offline-grid"><b>⚔ {g.offline.kills} kills</b><b>✦ {g.offline.exp.toLocaleString()} EXP</b><b>✧ {g.offline.job.toLocaleString()} Job EXP</b><b>🪙 {g.offline.zeny.toLocaleString()} Zeny</b></div><div className="offline-loot">{Object.entries(g.offline.drops).slice(0,8).map(([id,q])=><span key={id}>{items[id]?.icon} {items[id]?.name||id} x{q}</span>)}</div><button className="primary-btn" onClick={()=>g.setOffline(null)}>COLETAR</button></section></div>}
  </main>
}

function Character({g}:{g:ReturnType<typeof useGame>}){const jobs=classes.filter(c=>c.id!=='novice');return <div className="character-stack"><div className="character-panel"><img src="/sprites/swordsman.svg"/><div><h3>Knock · {g.classDef.name}</h3><p>Base Lv. <b>{g.save.baseLevel}</b> · Job Lv. <b>{g.save.jobLevel}</b> · Rebirth <b>{g.save.rebirths}</b></p><div className="attribute-grid"><span>ATK <b>{g.save.attack}</b></span><span>DEF <b>{g.save.defense}</b></span><span>HP <b>{g.save.maxHp}</b></span><span>SP <b>{g.save.maxSp}</b></span></div><button className="primary-btn" onClick={g.heal}>Recuperar HP/SP</button></div></div><div className="progression-box"><div className="progression-title"><h3>Atributos</h3><b>{g.save.statPoints} pontos disponíveis</b></div><div className="stat-grid">{(Object.keys(statLabels) as StatKey[]).map(k=><div className="stat-card" key={k}><span>{statLabels[k]}</span><strong>{g.save.stats[k]}</strong><button disabled={g.save.statPoints<=0} onClick={()=>g.addStat(k)}>+</button></div>)}</div></div><div className="progression-box"><div className="progression-title"><h3>Mudança de Classe</h3><small>{g.save.firstJobChosen?`Vocação permanente: ${g.classDef.name}.`:'Requisito: Base 10 + Job 10.'}</small></div><div className="class-grid">{jobs.map(c=>{const chosen=g.save.classId===c.id,locked=g.save.firstJobChosen&&!chosen,req=g.save.baseLevel<c.minBase||g.save.jobLevel<c.minJob;return <button key={c.id} disabled={locked||req||g.save.firstJobChosen} className={chosen?'selected':''} onClick={()=>g.chooseFirstJob(c.id)}><b>{c.icon} {c.name}</b><span>{c.description}</span><small>{chosen?'VOCAÇÃO ATUAL':locked?'BLOQUEADA':`Base ${c.minBase}+ · Job ${c.minJob}+`}</small></button>})}</div></div></div>}

function Inventory({g}:{g:ReturnType<typeof useGame>}){return <div className="inventory-grid">{Object.entries(g.save.inventory).filter(([,q])=>q>0).map(([id,q])=>{const it=items[id];if(!it)return null;return <div className={`item-slot ${it.rarity}`} key={id}><i>{it.icon}</i><b>{it.name}</b><small>{it.type}</small><em>x{q}</em><div className="item-actions">{it.type==='equipment'&&<button onClick={()=>g.equip(id)}>Equipar</button>}{it.type==='consumable'&&<button onClick={()=>g.consumeItem(id)}>Usar</button>}<button onClick={()=>g.sellItem(id)}>Vender {it.sell||1}z</button></div></div>})}</div>}

function Equipment({g}:{g:ReturnType<typeof useGame>}){const cards=Object.entries(g.save.inventory).filter(([id,q])=>q>0&&items[id]?.type==='card');return <div className="equipment-layout"><div className="paperdoll"><img src="/sprites/swordsman.svg"/></div><div className="equipment-slots">{slots.map(([slot,label])=>{const eq=g.save.equipped[slot],cardId=g.save.socketedCards[slot];return <div className="equip-row" key={slot}><span>{label}</span><b>{eq?items[eq]?.name:'Vazio'}</b><small>{cardId?`Card: ${items[cardId]?.name}`:'Sem card'}</small>{cardId&&<button onClick={()=>g.removeCard(slot)}>Remover card</button>}{eq&&cards.length>0&&<div className="card-picker">{cards.slice(0,5).map(([id])=><button key={id} onClick={()=>g.socketCard(slot,id)}>{items[id].icon} {items[id].name}</button>)}</div>}</div>})}<p>ATK total: <b>{g.save.attack}</b> · DEF total: <b>{g.save.defense}</b></p></div></div>}

function Maps({g,close}:{g:ReturnType<typeof useGame>;close:()=>void}){return <div className="map-grid expanded-grid">{maps.map(m=><button className={`map-card ${g.map.id===m.id?'selected':''}`} disabled={g.save.baseLevel<m.minLevel} key={m.id} onClick={()=>{g.changeMap(m.id);close()}}><span className={`map-thumb ${m.bg}`}/><strong>{m.name}</strong><small>{m.monster} Lv. {m.monsterLevel} · {m.element}</small><em>{m.exp} EXP · {m.jobExp} Job EXP · {m.zeny}z</em></button>)}</div>}

function Skills({g}:{g:ReturnType<typeof useGame>}){return <div><div className="progression-title"><h3>Árvore de Skills · {g.classDef.name}</h3><b>{g.save.jobPoints} Job Points</b></div><div className="skill-tree">{g.availableSkills.map(sk=>{const lvl=g.save.skillLevels[sk.id]||0,reqLevel=sk.requires?g.save.skillLevels[sk.requires.skillId]||0:0,ok=!sk.requires||reqLevel>=sk.requires.level;return <div className={`skill-node ${!ok?'skill-locked':''}`} key={sk.id}><div className="skill-icon">{sk.icon}</div><div><strong>{sk.name} <small>Lv. {lvl}/{sk.maxLevel}</small></strong><p>{sk.description}</p><span>{sk.kind==='passive'?'PASSIVA':`SP ${sk.spCost} · CD ${sk.cooldown}s`}</span>{sk.requires&&<em>Requer {sk.requires.skillId} Lv. {sk.requires.level}</em>}</div><button disabled={!ok||lvl>=sk.maxLevel||g.save.jobPoints<sk.jobPointCost} onClick={()=>g.learnSkill(sk.id)}>+</button></div>})}</div></div>}

function Shop({g}:{g:ReturnType<typeof useGame>}){return <div><div className="progression-title"><h3>Loja de Prontera</h3><b>{g.save.zeny.toLocaleString('pt-BR')} Zeny</b></div><div className="shop-grid">{shopItems.map(id=>{const it=items[id];return <div className="shop-card" key={id}><i>{it.icon}</i><b>{it.name}</b><small>{it.type} · {it.buy}z</small><button disabled={!it.buy||g.save.zeny<(it.buy||0)} onClick={()=>g.buyItem(id)}>Comprar</button></div>})}</div><h3 className="section-heading">Venda rápida</h3><div className="sell-list">{Object.entries(g.save.inventory).filter(([id,q])=>q>0&&items[id]).slice(0,18).map(([id,q])=><div key={id}><span>{items[id].icon} {items[id].name} x{q}</span><button onClick={()=>g.sellItem(id)}>Vender 1 · {items[id].sell||1}z</button></div>)}</div></div>}

function Bestiary({g}:{g:ReturnType<typeof useGame>}){return <div className="bestiary-grid">{maps.map(m=>{const kills=g.save.bestiary[m.monster]||0,seen=kills>0;return <div className={`bestiary-card ${seen?'seen':''}`} key={m.id}><div className="bestiary-head"><b>{seen?m.monster:'???'}</b><span>Lv. {m.monsterLevel}</span></div><p>{m.race} · {m.element}</p><p>HP {seen?m.monsterHp:'?'} · DEF {seen?m.monsterDef:'?'}</p><strong>{kills.toLocaleString('pt-BR')} derrotados</strong><div className="mini-drops">{m.drops.slice(0,4).map(dr=><span key={dr.itemId}>{seen||g.save.inventory[dr.itemId]>0?items[dr.itemId]?.name:'???'}</span>)}</div></div>})}</div>}

function Quests({g}:{g:ReturnType<typeof useGame>}){return <div className="quest-list">{quests.map(q=>{const progress=g.questProgress(q.id),done=progress>=q.amount,claimed=g.save.claimedQuests.includes(q.id);return <div className={`quest-card ${done?'done':''}`} key={q.id}><div><b>{q.name}</b><p>{q.description}</p><small>Progresso: {Math.min(progress,q.amount)}/{q.amount}</small></div><div><span>{q.reward.exp?`${q.reward.exp} EXP `:''}{q.reward.zeny?`· ${q.reward.zeny}z`:''}</span><button disabled={!done||claimed} onClick={()=>g.claimQuest(q.id)}>{claimed?'COLETADA':done?'COLETAR':'EM ANDAMENTO'}</button></div></div>})}</div>}

function AutoSettings({g}:{g:ReturnType<typeof useGame>}){return <div className="auto-settings"><div className="setting-row"><div><b>Curar automaticamente</b><small>Usa Heal/First Aid ou consumível quando o HP cair abaixo do limite.</small></div><select value={g.save.auto.healPct} onChange={e=>g.setAutoOption('healPct',Number(e.target.value))}><option value={20}>20%</option><option value={35}>35%</option><option value={50}>50%</option><option value={65}>65%</option></select></div><div className="setting-row"><div><b>Usar consumíveis</b><small>Apple, herbs e Honey quando não houver skill de cura disponível.</small></div><input type="checkbox" checked={g.save.auto.useConsumables} onChange={e=>g.setAutoOption('useConsumables',e.target.checked)}/></div><div className="setting-row"><div><b>Vender materiais comuns automaticamente</b><small>Converte materiais comuns em Zeny durante a caça.</small></div><input type="checkbox" checked={g.save.auto.autoSellCommon} onChange={e=>g.setAutoOption('autoSellCommon',e.target.checked)}/></div><h3>Skills automáticas</h3><div className="auto-skill-grid">{g.activeSkills.filter(sk=>sk.kind!=='heal').map(sk=><button className={g.save.auto.enabledSkills.includes(sk.id)?'active':''} disabled={(g.save.skillLevels[sk.id]||0)<=0} key={sk.id} onClick={()=>g.toggleAutoSkill(sk.id)}>{sk.icon} {sk.name} <small>Lv. {g.save.skillLevels[sk.id]||0}</small></button>)}</div></div>}

function Rebirth({g}:{g:ReturnType<typeof useGame>}){return <div className="rebirth-panel"><Crown size={52}/><h2>Rebirth</h2><p>Ao alcançar <b>Base Lv. 75</b>, você pode renascer. Níveis, classe, skills e inventário básico reiniciam, mas cada Rebirth concede bônus permanente.</p><div className="rebirth-stats"><span>Rebirths <b>{g.save.rebirths}</b></span><span>Rebirth Points <b>{g.save.rebirthPoints}</b></span><span>Bônus de combate <b>+{g.save.rebirths*8}%</b></span></div><button className="primary-btn danger-btn" disabled={!g.canRebirth} onClick={g.rebirth}>{g.canRebirth?'REALIZAR REBIRTH':`REQUER BASE LV. 75 · ATUAL ${g.save.baseLevel}`}</button><button className="ghost-danger" onClick={g.resetSave}>Apagar save local e iniciar novo jogo</button></div>}
